services:
  _defaults:
    autowire: true

  HeimrichHannot\GoogleMapsBundle\EventListener\ReplaceDynamicScriptTagsListener:
    public: true

  HeimrichHannot\GoogleMapsBundle\EventListener\LoadDataContainerListener:
    public: true

  HeimrichHannot\GoogleMapsBundle\EventListener\ReplaceInsertTagsListener:
    public: true
