services:

  HeimrichHannot\GoogleMapsBundle\EventSubscriber\:
    resource: '../../EventSubscriber/*'
    autowire: true
    autoconfigure: true

  HeimrichHannot\GoogleMapBundle\ConfigElementType\GoogleMapConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type', 'huh.reader.config_element_type']

  HeimrichHannot\GoogleMapsBundle\Collection\MapCollection: ~

  HeimrichHannot\GoogleMapsBundle\Manager\MapManager:
    shared: false
    autowire: true
  huh.google_maps.map_manager:
    alias: HeimrichHannot\GoogleMapsBundle\Manager\MapManager
    public: true

  huh.google_maps.overlay_manager:
    class: HeimrichHannot\GoogleMapsBundle\Manager\OverlayManager
    public: true
    shared: false
    arguments:
      - "@contao.framework"
      - "@huh.utils.model"
      - "@huh.utils.location"
      - "@huh.utils.file"
      - "@twig"
  HeimrichHannot\GoogleMapsBundle\Manager\OverlayManager:
    alias: 'huh.google_maps.overlay_manager'

  huh.google_maps.data_container.google_map:
    class: HeimrichHannot\GoogleMapsBundle\DataContainer\GoogleMap
    public: true
    arguments:
      - "@service_container"
  huh.google_maps.data_container.google_map_overlay:
    class: HeimrichHannot\GoogleMapsBundle\DataContainer\Overlay
    public: true
    arguments:
      - "@service_container"
  huh.google_maps.data_container.content:
    class: HeimrichHannot\GoogleMapsBundle\DataContainer\Content
    public: true
    arguments:
      - "@service_container"
  huh.google_maps.data_container.module:
    class: HeimrichHannot\GoogleMapsBundle\DataContainer\Module
    public: true
    arguments:
      - "@service_container"
  huh.google_maps.data_container.reader_config_element:
    class: HeimrichHannot\GoogleMapsBundle\DataContainer\ReaderConfigElement
    public: true
    arguments:
      - "@service_container"

  huh.google_maps.service.elevation:
    class: HeimrichHannot\GoogleMapsBundle\Service\ElevationService
    public: true
    arguments:
      - "@service_container"